### ISSUE TITLE
no data return on request

### ISSUE THREAD

**Issue by WarenGonzaga** [WarenGonzaga/buymeacoffee.js#23]
Someone reported this issue to me from the BMC Discord community.
After testing, it is a valid bug and needs to fix. 😢

The issue could be on how the client communicates with the API.

**Comment by thinkverse** [comment]
I know this is like two weeks after the issue was reported but it might not be a bug with the client, the token could simply have expired. The BMC API returns a JWT token, which contains an expiration timestamp. If that timestamp elapses then the token is no longer valid. I'm curious to learn how this issue was reported and tested. 👍

**Comment by WarenGonzaga** [comment]
Can't find the exact issue why there is no response when you console log the response. If anyone has an idea why we can discuss it here. Also, this is part of ``hacktoberfest``.

**Comment by WarenGonzaga** [comment]
Update, when you test it on postman it returns data. I guess the issue is on the wrapper itself (maybe). Still need to find the root cause so we can fix it as quickly as possible.

**Comment by WarenGonzaga** [comment]
> Hi! You test for this package or directly on BMC API ? @WarenGonzaga

I test directly on BMC API I believe the issue is on how we fetch the data using this wrapper.

**Comment by thomasbnt** [comment]
So weird. I tested with [Hoppscotch](https://hoppscotch.io/), not working and show me the login page.
![image](https://user-images.githubusercontent.com/14293805/136192955-f1fd83af-6311-4c7b-83fb-3ce0b515d2cb.png)

Directly with CURL, he work !
![image](https://user-images.githubusercontent.com/14293805/136193199-a98064db-4687-45bd-8659-fefcc884f5e6.png)


*Blur is private content, like emails, transactions, price...*

**Comment by WarenGonzaga** [comment]
@thomasbnt that's weird also on my end. You can directly call the API. I might rewrite the whole API wrapper. How about let's test the old version of this package? To be specific the alpha version. If it works meaning the latest version sucks.

**Comment by thinkverse** [comment]
> So weird. I tested with [Hoppscotch](https://hoppscotch.io/), not working and show me the login page.

That's what happens when the bearer token isn't present and/or invalid, it happens with postman as well.

<details>
<summary>Screenshots</summary>

![Screen Shot 2021-10-15 at 8 41 33 AM](https://user-images.githubusercontent.com/2221746/137443418-5ff58f9a-6872-4a91-886d-3167cd4d7b8a.png)
![Screen Shot 2021-10-15 at 8 41 55 AM](https://user-images.githubusercontent.com/2221746/137443423-096ef51c-45d1-48c4-8f4a-b2bcd3595996.png)
</details>

> I might rewrite the whole API wrapper.

Could it be how you call the methods on the wrapper? In your tests, you are using `async`, `await`. But in the documentation, you are calling the methods directly and not handling the promise.

```js
const coffee = new BMC(access.token);
coffee.Supporters(data => console.log(data));
```

This will result in a pending promise that's not handled since it's missing the `then` call.

```js
coffee.Supporters().then(data => console.log(data));
```

**Comment by thomasbnt** [comment]
> Are you able to fix it @thomasbnt?

Hello @WarenGonzaga, I don't know and I haven't tried with BMC.js yet

**Comment by WarenGonzaga** [comment]
Closing this issue for now, since it is now clear. Our example is confusing I'll update the documentation.

**Comment by warengonzaga** [comment]
We updated the example in the docs... kindly check our official docs page here: https://docs.warengonzaga.com/buymeacoffeejs
